# Generated by Django 4.1.1 on 2022-09-10 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_ab_negative_bloodstock_abnegative_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodstock',
            old_name='abpostive',
            new_name='abpositive',
        ),
        migrations.RenameField(
            model_name='bloodstock',
            old_name='apostive',
            new_name='apositive',
        ),
        migrations.RenameField(
            model_name='bloodstock',
            old_name='bnegative',
            new_name='opositive',
        ),
        migrations.RemoveField(
            model_name='bloodstock',
            name='bpostive',
        ),
        migrations.RemoveField(
            model_name='bloodstock',
            name='opostive',
        ),
    ]
